# Autogenerated by devscripts/update-version.py

__version__ = '2024.08.05.122024'

RELEASE_GIT_HEAD = '8b73a36063a5833baa7c5657a79fdc6b1dcd1b15'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'mfiferna/yt-dlp'

ORIGIN = 'mfiferna/yt-dlp'

_pkg_version = '2024.08.05.122024'
